// Generated by CoffeeScript 1.7.1
(function() {
  this.BadgeStatus = (function() {
    function BadgeStatus() {
      this.ba = chrome.browserAction;
    }

    BadgeStatus.prototype.update = function(status) {
      this.status = status;
      if (!this.status.login) {
        return this.ba.setBadgeText({
          text: "X"
        });
      } else if (!this.status.hasMail) {
        return this.ba.setBadgeText({
          text: ""
        });
      } else {
        return this.ba.setBadgeText({
          text: status.count
        });
      }
    };

    return BadgeStatus;

  })();

}).call(this);
