// Generated by CoffeeScript 1.7.1
(function() {
  this.Cybouz = (function() {
    function Cybouz() {}

    Cybouz.CB_URL = "https://www.itsol.co.jp/cgi-bin/cb6/ag.cgi";

    Cybouz.CB_FOLDER_URL = "" + Cybouz.CB_URL + "?page=MyFolderIndex";

    Cybouz.CB_CHECK_URL = "" + Cybouz.CB_URL + "?page=MailCheckInterval&info=&notimecard=1";

    Cybouz.prototype.isCbUrl = function(url) {
      return url.indexOf(CB_URL) !== -1;
    };

    return Cybouz;

  })();

}).call(this);

//# sourceMappingURL=cybouz.map
