// Generated by CoffeeScript 1.7.1
(function() {
  this.Cybozu = (function() {
    function Cybozu() {
      this.cbUrl = "https://www.itsol.co.jp/cgi-bin/cb6/ag.cgi";
      this.cbFolderUrl = "" + this.cbUrl + "?page=MyFolderIndex";
      this.cbReciveInPageUrl = "" + this.cbUrl + "?page=MyFolderIndex#receive";
      this.cbChekcerUrl = "" + this.cbUrl + "?page=MailCheckInterval&info=&notimecard=1";
    }

    Cybozu.prototype.isCbUrl = function(url) {
      return url.indexOf(this.cbUrl) !== -1;
    };

    Cybozu.prototype.getChckerUrl = function() {
      return this.cbChekcerUrl;
    };

    Cybozu.prototype.getActiveTab = function() {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return chrome.tabs.query({
            url: "" + _this.cbUrl + "*"
          }, function(tabs) {
            var tab, _i, _len;
            for (_i = 0, _len = tabs.length; _i < _len; _i++) {
              tab = tabs[_i];
              if ((tab.url != null) && _this.isCbUrl(tab.url)) {
                resolve(tab);
              }
            }
            return reject();
          });
        };
      })(this));
    };

    Cybozu.prototype.pageUpdated = function(callback) {
      return chrome.tabs.onUpdated.addListener((function(_this) {
        return function(tabId, changeInfo, tab) {
          if ((tab.url != null) && _this.isCbUrl(tab.url)) {
            return callback(tabId, changeInfo, tab);
          }
        };
      })(this));
    };

    Cybozu.prototype.openPage = function() {
      return this.getActiveTab().then((function(_this) {
        return function(tab) {
          return chrome.tabs.update(tab.id, {
            selected: true
          });
        };
      })(this), (function(_this) {
        return function() {
          return chrome.tabs.create({
            url: _this.cbFolderUrl
          });
        };
      })(this));
    };

    Cybozu.prototype.openPageAndMailCheck = function() {
      return this.getActiveTab().then((function(_this) {
        return function(tab) {
          return chrome.tabs.update(tab.id, {
            selected: true,
            url: _this.cbReciveInPageUrl
          });
        };
      })(this), (function(_this) {
        return function() {
          return chrome.tabs.create({
            url: _this.cbReciveInPageUrl
          });
        };
      })(this));
    };

    return Cybozu;

  })();

}).call(this);
