// Generated by CoffeeScript 1.7.1
(function() {
  this.LoadingAnimation = (function() {
    function LoadingAnimation() {
      this.timerId_ = 0;
      this.maxCount_ = 8;
      this.current_ = 0;
      this.maxDot_ = 4;
    }

    LoadingAnimation.prototype.paintFrame = function() {
      var i, text;
      text = "";
      i = 0;
      while (i < this.maxDot_) {
        text += (i === this.current_ ? "." : " ");
        i++;
      }
      if (this.current_ >= this.maxDot_) {
        text += "";
      }
      chrome.browserAction.setBadgeText({
        text: text
      });
      this.current_++;
      if (this.current_ === this.maxCount_) {
        return this.current_ = 0;
      }
    };

    LoadingAnimation.prototype.start = function() {
      if (this.timerId_) {
        return;
      }
      return this.timerId_ = window.setInterval((function(_this) {
        return function() {
          return _this.paintFrame();
        };
      })(this), 100);
    };

    LoadingAnimation.prototype.stop = function() {
      if (!this.timerId_) {
        return;
      }
      window.clearInterval(this.timerId_);
      return this.timerId_ = 0;
    };

    return LoadingAnimation;

  })();

}).call(this);

//# sourceMappingURL=loading_animation.map
