// Generated by CoffeeScript 1.7.1
(function() {
  var PopupViewModel,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  PopupViewModel = (function() {
    function PopupViewModel() {
      this.onReceive = __bind(this.onReceive, this);
      this.receive = __bind(this.receive, this);
      this.open = __bind(this.open, this);
      this.service = chrome.extension.getBackgroundPage().getService();
      this.service.addEventListener({
        onReceive: this.onReceive
      });
      this.content = ko.observable("");
      this.hasMail = ko.observable(false);
    }

    PopupViewModel.prototype.open = function() {
      return this.service.open();
    };

    PopupViewModel.prototype.receive = function() {
      return this.service.receive();
    };

    PopupViewModel.prototype.onReceive = function(status) {
      var content;
      content = status.content != null ? status.content.innerText : "";
      this.content(content);
      return this.hasMail(status.hasMail);
    };

    PopupViewModel.prototype.start = function() {
      return ko.applyBindings(this);
    };

    return PopupViewModel;

  })();

  $(function() {
    return new PopupViewModel().start();
  });

}).call(this);

//# sourceMappingURL=browser_action.map
